config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    member do
      get "push"
    end
  end
  
  post "feeds/:id" => "feeds#update_or_create"

  root 'feeds#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
    require "net/http"
    require "uri"

    validates_presence_of :name
    # validates_presence_of :original_url
    validates_uniqueness_of :name
    self.primary_key = "name"

    before_save :parameterize_name
    
    def parameterize_name
        self.name = self.name.parameterize if self.name.present?
    end
    
    def to_param
        self.name || self.id    
    end
    
    def push

        if self.push_url.present?
            begin
                uri = URI.parse( self.push_url )
        
                http = Net::HTTP.new(uri.host, uri.port)
                http.use_ssl = (uri.scheme == "https")
                request = Net::HTTP::Post.new(uri.request_uri)
                request.set_form_data({feed: {last_body: "My query #{Time.now}"}})
                
                response = http.request(request)
                
                self.pushed_at = Time.now if response.status == 200
                [true, :success]
            rescue
                # tried to push but failed
                [false, :tried_to_push_but_failed]
            end
        else
            puts "no push_url"
            [false, :no_push_url_defined]
        end
    end
    
    def fetch

        begin
            url = URI.parse( self.original_url )
            req = Net::HTTP::Get.new(url.to_s)
            http = Net::HTTP.new(url.host, url.port)
            http.use_ssl = (url.scheme == "https")
            response = http.request(req)
    
            self.last_body = response.body
            
            self.last_pulled_at = Time.now
        rescue
            # unable
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy, :push]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    render xml: @feed.last_body || "<no-content></no-content>"
  end

  def push
    render json: @feed.push
  end
  
  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  def update_or_create
    @feed = Feed.find_by_name( params[:id].parameterize ) || Feed.create!( name: params[:id].parameterize )
    
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    @feed.fetch if @feed.valid?
    
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    @feed.fetch if @feed.valid?
    
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :original_url, :push_url, :last_body, :last_format)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :original_url %><br>
    <%= f.text_field :original_url %>
  </div>
  
  <div class="field">
    <%= f.label :push_url %><br>
    <%= f.text_field :push_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> | 
<%= link_to 'Destroy', @feed, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feeds</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Original url</th>
      <th>Push url</th>
      <th>Last body</th>
      <th>Last format</th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= link_to feed.name, edit_feed_path(feed) %></td>
        <td><%= feed.original_url %> <%= "(Last fetched #{time_ago_in_words(feed.last_pulled_at)} ago)" if feed.last_pulled_at %></td>
        <td><%= feed.push_url %> <%= "(Last pushed #{time_ago_in_words(feed.last_pushed_at)} ago)" if feed.last_pushed_at %></td>
        <td><%= feed.last_body.present? ? feed.last_body.first(100) : "" %> (<%= link_to 'Show more...', feed %>)</td>
        <td><%= feed.last_format %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path, class: "btn btn-default" %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Original url:</strong>
  <%= @feed.original_url %>
</p>

<p>
  <strong>Last pulled at:</strong>
  <%= @feed.last_pulled_at %>
</p>

<p>
  <strong>Last pushed at:</strong>
  <%= @feed.last_pushed_at %>
</p>

<p>
  <strong>Last body:</strong>
  <%= @feed.last_body %>
</p>

<p>
  <strong>Last format:</strong>
  <%= @feed.last_format %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %> | 
<%= link_to 'Destroy', @feed, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" type="text/css" />

  <%= csrf_meta_tags %>
</head>
<body>
        <div class="container">
            <div class="row">
                <%= yield %>  
            </div>
        </div>


</body>
</html>